[project]
authors = [{name = "sila1404", email = "silamany1404@gmail.com"}]
description = "Add a short description here"
name = "Lao_air_writting"
requires-python = ">= 3.11, <3.12"
version = "0.1.0"
dependencies = ["mediapipe>=0.10.14,<0.11", "tensorflow>=2.14.0,<3"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.pypi-dependencies]
lao_air_writting = { path = ".", editable = true }

[tool.pixi.dependencies]
opencv = ">=4.10.0,<5"
numpy = "<2"

[tool.pixi.tasks]
collect = "python ./src/collect_data/main.py"
augment = "python ./src/augment_image/main.py"
